FROM node:18 as base

WORKDIR /usr/src/app

COPY package.json package.json
COPY yarn.lock yarn.lock
COPY src src
COPY tsconfig*.json .
COPY rollup.config.js rollup.config.js

# Build and pack agrippa

RUN yarn install --frozen-lockfile
RUN yarn build
RUN yarn pack

# Build tests file

COPY test test
RUN yarn tsc test/end-to-end/end-to-end.test.ts

FROM node:14 as test
WORKDIR /usr/src/app

# Get the tarball from base

COPY --from=base /usr/src/app/agrippa-*.tgz ./

# Setup and run tests

RUN yarn init -y
RUN find . -name "agrippa*.tgz" | xargs -I % sh -c "yarn add --dev %"
RUN yarn add --dev fast-glob@^3.2.7 mocha@^10.0.0

COPY test/end-to-end end-to-end
COPY --from=base /usr/src/app/test/end-to-end/end-to-end.test.js end-to-end/end-to-end.test.js

CMD ["yarn", "mocha", "end-to-end/end-to-end.test.js"]