FROM node:14 as base

WORKDIR /usr/src/app

COPY package.json package.json
COPY yarn.lock yarn.lock
COPY src src
COPY tsconfig.json tsconfig.json
COPY test/integration integration

RUN yarn install
RUN yarn build
RUN yarn pack

FROM node:14 as test
WORKDIR /usr/src/app

COPY --from=base /usr/src/app/agrippa-v1.2.1.tgz ./agrippa.tgz
RUN npm i -g agrippa.tgz

CMD ["npx", "agrippa", "gen", "aa"]