import { joinLines } from '../../utils';

/**
 * Returns the contents of a config file to be generated by the `init` command.
 */
export function getConfigTemplate(bare: boolean) {
  return bare
    ? joinLines(
      '// @ts-check',
      '',
      'export default {',
      '  options: {}',
      '};'
    )
    : joinLines(
      '// @ts-check',
      "import { defineConfig } from 'agrippa';",
      '',
      'export default defineConfig({',
      '  options: {}',
      '});',
    );
}